import type { Todo, TodoPlanningState, TodoPriority, TodoWorkflowStatus } from "../types/todo";
import type { QueuedTodoMutation } from "./offlineTodoQueue";

const record = (value: unknown): Record<string, unknown> | null =>
  value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null;

const stringIds = (value: unknown) =>
  Array.isArray(value) ? value.filter((id): id is string => typeof id === "string") : [];

const pathId = (path: string) => path.split("/").filter(Boolean).at(-1) || "";

const isPlanningState = (value: unknown): value is TodoPlanningState =>
  value === "INBOX" || value === "SCHEDULED" || value === "SOMEDAY" || value === "WAITING";
const isWorkflowStatus = (value: unknown): value is TodoWorkflowStatus =>
  value === "TODO" || value === "IN_PROGRESS" || value === "BLOCKED" || value === "DONE";
const isPriority = (value: unknown): value is TodoPriority =>
  value === "LOW" || value === "MEDIUM" || value === "HIGH";

/**
 * Apply persisted, not-yet-confirmed mutations over an API snapshot.
 *
 * Only replays operations recorded in IndexedDB. No records are persisted here,
 * and no server writes happen from this function. FAILED mutations stay visible
 * until the user fixes/retries them.
 */
export function replayQueuedTodoMutations(serverTodos: readonly Todo[], queued: readonly QueuedTodoMutation[]): Todo[] {
  const byId = new Map(serverTodos.map((todo) => [todo.id, todo]));

  for (const mutation of [...queued].sort((a, b) => (a.id ?? 0) - (b.id ?? 0))) {
    const body = record(mutation.body);
    if (mutation.kind === "CREATE") {
      if (!mutation.path.startsWith("/api/offline/todos/") || !body) continue;
      const id = pathId(mutation.path);
      if (!id || typeof body.title !== "string" || !body.title.trim()) continue;
      // Server already has this UUID => replay was acknowledged by D1.
      // Leave the server record intact; later queued edits still apply.
      if (byId.has(id)) continue;
      const status = isWorkflowStatus(body.workflowStatus) ? body.workflowStatus : "TODO";
      const completed = typeof body.completed === "boolean" ? body.completed : status === "DONE";
      const date = typeof body.date === "string" ? body.date : "";
      if (!date) continue;
      byId.set(id, {
        ...(body as Partial<Todo>),
        id,
        title: body.title,
        date,
        planningState: isPlanningState(body.planningState) ? body.planningState : "SCHEDULED",
        workflowStatus: completed ? "DONE" : status === "DONE" ? "TODO" : status,
        priority: isPriority(body.priority) ? body.priority : "MEDIUM",
        completed,
        archived: body.archived === true,
        createdAt: mutation.createdAt,
        updatedAt: mutation.createdAt,
      });
      continue;
    }

    if (mutation.kind === "TRASH") {
      byId.delete(mutation.path.split("/").at(-2) || "");
      continue;
    }
    if (mutation.kind === "BULK_TRASH") {
      for (const id of stringIds(body?.ids)) byId.delete(id);
      continue;
    }
    if (mutation.kind === "BULK_UPDATE") {
      const action = record(body?.action);
      if (!action) continue;
      for (const id of stringIds(body?.ids)) {
        const todo = byId.get(id);
        if (!todo) continue;
        if (action.type === "DATE" && typeof action.value === "string")
          byId.set(id, { ...todo, date: action.value, planningState: "SCHEDULED", updatedAt: mutation.createdAt });
        else if (action.type === "PRIORITY" && isPriority(action.value))
          byId.set(id, { ...todo, priority: action.value, updatedAt: mutation.createdAt });
        else if (action.type === "WORKFLOW_STATUS" && isWorkflowStatus(action.value))
          byId.set(id, { ...todo, workflowStatus: action.value, completed: action.value === "DONE", updatedAt: mutation.createdAt });
        else if (action.type === "PROJECT" && (typeof action.value === "string" || action.value === null))
          byId.set(id, { ...todo, projectId: action.value || undefined, milestoneId: undefined, parentTodoId: undefined, updatedAt: mutation.createdAt });
      }
      continue;
    }

    if (mutation.kind !== "UPDATE" || !body) continue;
    const id = mutation.path.includes("/completion") ? mutation.path.split("/").at(-2) || "" : pathId(mutation.path);
    const todo = byId.get(id);
    if (!todo) continue;
    if (mutation.path.endsWith("/completion")) {
      if (typeof body.completed !== "boolean") continue;
      byId.set(id, {
        ...todo,
        completed: body.completed,
        workflowStatus: body.completed ? "DONE" : todo.workflowStatus === "DONE" ? "TODO" : todo.workflowStatus,
        updatedAt: mutation.createdAt,
      });
      continue;
    }
    const previousCategoryId = todo.categoryId;
    // Updates are full Todo payloads generated by toTodoRequestBody.
    // Do not allow malformed payloads to override identity/creation.
    const changes = { ...(body as Partial<Todo>) };
    delete changes.id;
    delete changes.userId;
    delete changes.createdAt;
    delete changes.category;
    if (typeof changes.title !== "string" || typeof changes.date !== "string") continue;
    const next = { ...todo, ...changes, updatedAt: mutation.createdAt };
    if (next.categoryId !== previousCategoryId) next.category = undefined;
    byId.set(id, next);
  }

  return Array.from(byId.values());
}
