import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/d1";
import { Hono } from "hono";
import { musicLinks, topicLinks, topics } from "../db/schema";
import { serializeMusicLink, serializeTopicLink, serializeTopics } from "../serializers";
import type { Bindings, Variables } from "../types";
import { newId, normalizeIcon, nowIso, optional, pagination } from "../utils";
import { musicLinkInputSchema, topicInputSchema, topicLinkInputSchema } from "../validation";

export const libraryRoutes = new Hono<{ Bindings: Bindings; Variables: Variables }>();

libraryRoutes.get("/topics", async (c) => {
  const db = drizzle(c.env.DB); const page = pagination((name) => c.req.query(name)); const filters = [eq(topics.userId, c.get("userId"))]; const status = c.req.query("status");
  if (status === "IDEA" || status === "WRITING" || status === "DONE") filters.push(eq(topics.status, status));
  const rows = await db.select().from(topics).where(and(...filters)).orderBy(desc(topics.updatedAt)).limit(page.limit).offset(page.offset); let serialized = await serializeTopics(db, rows);
  const keyword = c.req.query("keyword")?.trim().toLowerCase(), tag = c.req.query("tag")?.trim().replace(/^#/, "").toLowerCase();
  if (keyword) serialized = serialized.filter((topic) => `${topic.title} ${topic.memo || ""} ${topic.tags.join(" ")} ${topic.links.map((link) => `${link.title || ""} ${link.url} ${link.description || ""}`).join(" ")}`.toLowerCase().includes(keyword));
  if (tag) serialized = serialized.filter((topic) => topic.tags.some((value) => value.toLowerCase() === tag));
  return c.json({ topics: serialized, nextCursor: page.next(rows.length) });
});
libraryRoutes.post("/topics", async (c) => { const input = topicInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const now = nowIso(); const row = { id: newId(), userId: c.get("userId"), title: input.title, memo: optional(input.memo), status: input.status, tagsJson: JSON.stringify(input.tags), icon: normalizeIcon(input.icon), createdAt: now, updatedAt: now }; await db.insert(topics).values(row); return c.json({ topic: (await serializeTopics(db, [row]))[0] }, 201); });
libraryRoutes.get("/topics/:id", async (c) => { const db = drizzle(c.env.DB); const [row] = await db.select().from(topics).where(and(eq(topics.id, c.req.param("id")), eq(topics.userId, c.get("userId")))).limit(1); return row ? c.json({ topic: (await serializeTopics(db, [row]))[0] }) : c.json({ message: "주제를 찾을 수 없습니다." }, 404); });
libraryRoutes.put("/topics/:id", async (c) => { const input = topicInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const id = c.req.param("id"), userId = c.get("userId"); const [existing] = await db.select().from(topics).where(and(eq(topics.id, id), eq(topics.userId, userId))).limit(1); if (!existing) return c.json({ message: "주제를 찾을 수 없습니다." }, 404); await db.update(topics).set({ title: input.title, memo: optional(input.memo), status: input.status, tagsJson: JSON.stringify(input.tags), icon: normalizeIcon(input.icon), updatedAt: nowIso() }).where(eq(topics.id, id)); const [row] = await db.select().from(topics).where(eq(topics.id, id)); return c.json({ topic: (await serializeTopics(db, [row]))[0] }); });
libraryRoutes.delete("/topics/:id", async (c) => { const db = drizzle(c.env.DB); await db.delete(topics).where(and(eq(topics.id, c.req.param("id")), eq(topics.userId, c.get("userId")))); return c.json({ ok: true }); });

libraryRoutes.post("/topics/:id/links", async (c) => { const input = topicLinkInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const topicId = c.req.param("id"); const [topic] = await db.select({ id: topics.id }).from(topics).where(and(eq(topics.id, topicId), eq(topics.userId, c.get("userId")))); if (!topic) return c.json({ message: "주제를 찾을 수 없습니다." }, 404); const now = nowIso(); const row = { id: newId(), topicId, title: optional(input.title), url: input.url, description: optional(input.description), createdAt: now, updatedAt: now }; await db.insert(topicLinks).values(row); return c.json({ link: serializeTopicLink(row) }, 201); });
libraryRoutes.put("/topics/:id/links/:linkId", async (c) => { const input = topicLinkInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const id = c.req.param("id"), linkId = c.req.param("linkId"); const [link] = await db.select({ id: topicLinks.id }).from(topicLinks).innerJoin(topics, eq(topicLinks.topicId, topics.id)).where(and(eq(topicLinks.id, linkId), eq(topics.id, id), eq(topics.userId, c.get("userId")))); if (!link) return c.json({ message: "링크를 찾을 수 없습니다." }, 404); await db.update(topicLinks).set({ title: optional(input.title), url: input.url, description: optional(input.description), updatedAt: nowIso() }).where(eq(topicLinks.id, linkId)); const [row] = await db.select().from(topicLinks).where(eq(topicLinks.id, linkId)); return c.json({ link: serializeTopicLink(row) }); });
libraryRoutes.delete("/topics/:id/links/:linkId", async (c) => { const db = drizzle(c.env.DB); const matches = db.select({ id: topicLinks.id }).from(topicLinks).innerJoin(topics, eq(topicLinks.topicId, topics.id)).where(and(eq(topicLinks.id, c.req.param("linkId")), eq(topics.id, c.req.param("id")), eq(topics.userId, c.get("userId")))); const [link] = await matches; if (link) await db.delete(topicLinks).where(eq(topicLinks.id, link.id)); return c.json({ ok: true }); });

libraryRoutes.get("/music-links", async (c) => { const db = drizzle(c.env.DB); const page = pagination((name) => c.req.query(name)); const rows = await db.select().from(musicLinks).where(eq(musicLinks.userId, c.get("userId"))).orderBy(desc(musicLinks.updatedAt)).limit(page.limit).offset(page.offset); return c.json({ musicLinks: rows.map(serializeMusicLink), nextCursor: page.next(rows.length) }); });
libraryRoutes.post("/music-links", async (c) => { const input = musicLinkInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const now = nowIso(); const row = { id: newId(), userId: c.get("userId"), title: input.title, url: input.url, provider: input.provider, memo: optional(input.memo), createdAt: now, updatedAt: now }; await db.insert(musicLinks).values(row); return c.json({ musicLink: serializeMusicLink(row) }, 201); });
libraryRoutes.put("/music-links/:id", async (c) => { const input = musicLinkInputSchema.parse(await c.req.json()); const db = drizzle(c.env.DB); const id = c.req.param("id"), userId = c.get("userId"); const [existing] = await db.select().from(musicLinks).where(and(eq(musicLinks.id, id), eq(musicLinks.userId, userId))).limit(1); if (!existing) return c.json({ message: "음악 링크를 찾을 수 없습니다." }, 404); await db.update(musicLinks).set({ title: input.title, url: input.url, provider: input.provider, memo: optional(input.memo), updatedAt: nowIso() }).where(eq(musicLinks.id, id)); const [row] = await db.select().from(musicLinks).where(eq(musicLinks.id, id)); return c.json({ musicLink: serializeMusicLink(row) }); });
libraryRoutes.delete("/music-links/:id", async (c) => { const db = drizzle(c.env.DB); await db.delete(musicLinks).where(and(eq(musicLinks.id, c.req.param("id")), eq(musicLinks.userId, c.get("userId")))); return c.json({ ok: true }); });
