import { FormEvent, ReactNode, useEffect, useState } from "react";
import { CalendarCheck2 } from "lucide-react";
import { api, ApiError, jsonBody } from "../../lib/api/client";

type Session = { authenticated: boolean; username?: string };
export function AuthGate({ children }: { children: (logout: () => Promise<void>) => ReactNode }) {
  const [session, setSession] = useState<Session | null>(null); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { api<Session>("/api/auth/session").then(setSession).catch(() => setSession({ authenticated: false })); const expire = () => setSession({ authenticated: false }); window.addEventListener("auth:unauthorized", expire); return () => window.removeEventListener("auth:unauthorized", expire); }, []);
  const login = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(""); try { const next = await api<Session>("/api/auth/login", { method: "POST", ...jsonBody({ username, password }) }); setPassword(""); setSession(next); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "로그인에 실패했습니다."); } finally { setSubmitting(false); } };
  const logout = async () => { try { await api("/api/auth/logout", { method: "POST" }); } finally { setSession({ authenticated: false }); } };
  if (!session) return <div className="flex min-h-screen items-center justify-center text-ink-300">인증 상태 확인 중...</div>;
  if (session.authenticated) return <>{children(logout)}</>;
  return <main className="flex min-h-screen items-center justify-center px-4"><form onSubmit={login} className="w-full max-w-sm space-y-5 rounded-2xl border border-ink-700 bg-ink-900 p-7 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-accent-500 text-white"><CalendarCheck2 size={22} /></div><div><h1 className="text-xl font-bold text-ink-100">Todo Planner</h1><p className="text-sm text-ink-400">개인 계정으로 로그인하세요.</p></div></div><label className="block text-sm font-semibold text-ink-200">사용자명<input autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} className="mt-2 w-full rounded-lg border border-ink-700 bg-ink-950 px-3 py-2.5 text-ink-100 outline-none focus:border-accent-500" required /></label><label className="block text-sm font-semibold text-ink-200">비밀번호<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-lg border border-ink-700 bg-ink-950 px-3 py-2.5 text-ink-100 outline-none focus:border-accent-500" required /></label>{error ? <p role="alert" className="text-sm text-red-300">{error}</p> : null}<button disabled={submitting} className="w-full rounded-lg bg-accent-500 px-4 py-2.5 font-semibold text-white disabled:opacity-60">{submitting ? "로그인 중..." : "로그인"}</button></form></main>;
}
